# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be98deaccbcd9906ab2034f88a6b2e61b41af2c13549102c5f1ed28de856328201b389a4e1e90b89881d9ad0b212abda99ec5056fabb25b595b3cb6bfb57f835

test:
  secret_key_base: b05b86bfd3992c2833e3ed9d7b949f5f90d76d6c39bf63d17792b5e33730a8e2a1a4e31699ffd9b6c28314387f9acde5d6ca68b5fe7795bdb5d87f48201fa586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
